version: '3.8'

services:
  db:
    image: postgres:16
    container_name: moderation-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moderation_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: moderation-api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: moderation_db
      PERSPECTIVE_API_KEY: ${PERSPECTIVE_API_KEY}
      API_KEY: ${API_KEY}
    volumes:
      - .:/app
    command: npm run start:dev

volumes:
  pgdata:
